[package]
name = "dynrsaur"
version = "0.1.0"
edition = "2021"

[dependencies]
const_panic = "0.2.11"
paste = "1.0.15"
sealed = "0.6.0"
typenum = { version = "1.17.0", features = ["const-generics"] }
